# -*- mode: ruby -*-
# vi: set ft=ruby :
NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 2
NUM_LB_NODE = 1

IP_NW = "172.16.79."
MASTER_IP_START = 10
NODE_IP_START = 20
LB_IP_START = 30

Vagrant.configure("2") do |config|
#  config.vm.box = "hashicorp/bionic64"
  config.vm.box = "generic/centos7"
  config.vm.box_check_update = false

  # Master Node(s)
  (1..NUM_MASTER_NODE).each do |i|
    config.vm.define "master-#{i}" do |node|
      node.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "2"
        v.vmx["ethernet1.vnet"] = "vmnet2"
      end
      node.vm.hostname = "master-#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
      if i == NUM_MASTER_NODE
      #Ansible Playbook Provisioner for masters
        node.vm.provision :ansible do |ansible|
          ansible.playbook = "./playbooks/infra_masters.yaml"
          ansible.inventory_path = "./inv/hosts"
          ansible.limit = "all"
        end
      end
    end
  end
  # Worker Nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "worker-#{i}" do |node|
      node.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "2048"
        v.vmx["numvcpus"] = "2"
        v.vmx["ethernet1.vnet"] = "vmnet2"
      end
      node.vm.hostname = "worker-#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
      if i == NUM_WORKER_NODE
      # Ansible Playbook Provisioner for workers
        node.vm.provision :ansible do |ansible|
          ansible.playbook = "./playbooks/infra_workers.yaml"
          ansible.inventory_path = "./inv/hosts"
          ansible.limit = "all"
        end
      end
    end
  end
  # Load Balancer Node(s)
  (1..NUM_LB_NODE).each do |i|
    config.vm.define "lb-#{i}" do |node|
      node.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = "512"
        v.vmx["numvcpus"] = "1"
        v.vmx["ethernet1.vnet"] = "vmnet2"
      end
      node.vm.hostname = "lb-#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{LB_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22, host: "#{2730 + i}"
      if i == NUM_LB_NODE
      # Ansible Playbook Provisioner for the Load Balancer
        node.vm.provision :ansible do |ansible|
          ansible.playbook = "./playbooks/infra_lb.yaml"
          ansible.inventory_path = "./inv/hosts"
          ansible.limit = "all"
        end
      end
    end
  end
end